-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Department"
(
    "DepartmentId" serial NOT NULL,
    "Code" character varying(10) COLLATE pg_catalog."default",
    "Name" character varying(50) COLLATE pg_catalog."default",
    "FacultyId" integer,
    CONSTRAINT "Department_pkey" PRIMARY KEY ("DepartmentId")
);

CREATE TABLE IF NOT EXISTS public."Department_Head"
(
    "DepartmentHeadId" serial NOT NULL,
    "EmployeeId" integer,
    "Experience" integer,
    CONSTRAINT "Department_Head_pkey" PRIMARY KEY ("DepartmentHeadId")
);

CREATE TABLE IF NOT EXISTS public."Employee"
(
    "EmployeeId" serial NOT NULL,
    "DeptId" integer,
    "FullName" character varying(50) COLLATE pg_catalog."default",
    "Position" character varying(50) COLLATE pg_catalog."default",
    "Salary" numeric(10, 2),
    "ChiefId" integer,
    "RoleId" integer,
    "Login" character varying(50) COLLATE pg_catalog."default",
    "PasswordHash" character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "Employee_pkey" PRIMARY KEY ("EmployeeId")
);

CREATE TABLE IF NOT EXISTS public."Engineer"
(
    "EngineerId" serial NOT NULL,
    "EmployeeId" integer,
    "Specialty" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Engineer_pkey" PRIMARY KEY ("EngineerId")
);

CREATE TABLE IF NOT EXISTS public."Exam"
(
    "ExamId" serial NOT NULL,
    "ExamDate" date,
    "SubjectId" integer,
    "StudentId" integer,
    "TeacherId" integer,
    "Auditorium" character varying(20) COLLATE pg_catalog."default",
    "Grade" integer,
    CONSTRAINT "Exam_pkey" PRIMARY KEY ("ExamId")
);

CREATE TABLE IF NOT EXISTS public."Faculty"
(
    "FacultyId" serial NOT NULL,
    "Abbreviation" character(5) COLLATE pg_catalog."default",
    "Name" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Faculty_pkey" PRIMARY KEY ("FacultyId")
);

CREATE TABLE IF NOT EXISTS public."Role"
(
    "RoleId" serial NOT NULL,
    "Name" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Role_pkey" PRIMARY KEY ("RoleId")
);

CREATE TABLE IF NOT EXISTS public."Specialty"
(
    "SpecialtyId" serial NOT NULL,
    "Code" character varying(20) COLLATE pg_catalog."default",
    "Name" character varying(100) COLLATE pg_catalog."default",
    "DeptId" integer,
    CONSTRAINT "Specialty_pkey" PRIMARY KEY ("SpecialtyId")
);

CREATE TABLE IF NOT EXISTS public."Specialty_Subject"
(
    "SpecialtySubjectId" serial NOT NULL,
    "SpecialtyId" integer,
    "SubjectId" integer,
    CONSTRAINT "Specialty_Subject_pkey" PRIMARY KEY ("SpecialtySubjectId")
);

CREATE TABLE IF NOT EXISTS public."Student"
(
    "StudentId" serial NOT NULL,
    "RegistrationNumber" character varying(20) COLLATE pg_catalog."default",
    "FullName" character varying(50) COLLATE pg_catalog."default",
    "SpecialtyId" integer,
    "Login" character(50) COLLATE pg_catalog."default",
    "PasswordHash" character(50) COLLATE pg_catalog."default",
    CONSTRAINT "Student_pkey" PRIMARY KEY ("StudentId")
);

CREATE TABLE IF NOT EXISTS public."Subject"
(
    "SubjectId" serial NOT NULL,
    "Code" character varying(10) COLLATE pg_catalog."default",
    "Hours" integer,
    "Name" character varying(100) COLLATE pg_catalog."default",
    "ExecutorDeptId" integer,
    CONSTRAINT "Subject_pkey" PRIMARY KEY ("SubjectId")
);

CREATE TABLE IF NOT EXISTS public."Teacher"
(
    "TeacherId" serial NOT NULL,
    "EmployeeId" integer,
    "Title" character varying(50) COLLATE pg_catalog."default",
    "Degree" character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Teacher_pkey" PRIMARY KEY ("TeacherId")
);

ALTER TABLE IF EXISTS public."Department"
    ADD CONSTRAINT "Department_FacultyId_fkey" FOREIGN KEY ("FacultyId")
    REFERENCES public."Faculty" ("FacultyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Department_Head"
    ADD CONSTRAINT "Department_Head_EmployeeId_fkey" FOREIGN KEY ("EmployeeId")
    REFERENCES public."Employee" ("EmployeeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Employee"
    ADD CONSTRAINT "Employee_ChiefId_fkey" FOREIGN KEY ("ChiefId")
    REFERENCES public."Employee" ("EmployeeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."Employee"
    ADD CONSTRAINT "Employee_DeptId_fkey" FOREIGN KEY ("DeptId")
    REFERENCES public."Department" ("DepartmentId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Employee"
    ADD CONSTRAINT "Employee_RoleId_fkey" FOREIGN KEY ("RoleId")
    REFERENCES public."Role" ("RoleId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Engineer"
    ADD CONSTRAINT "Engineer_EmployeeId_fkey" FOREIGN KEY ("EmployeeId")
    REFERENCES public."Employee" ("EmployeeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Exam"
    ADD CONSTRAINT "Exam_StudentId_fkey" FOREIGN KEY ("StudentId")
    REFERENCES public."Student" ("StudentId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Exam"
    ADD CONSTRAINT "Exam_SubjectId_fkey" FOREIGN KEY ("SubjectId")
    REFERENCES public."Subject" ("SubjectId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Exam"
    ADD CONSTRAINT "Exam_TeacherId_fkey" FOREIGN KEY ("TeacherId")
    REFERENCES public."Employee" ("EmployeeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Specialty"
    ADD CONSTRAINT "Specialty_DeptId_fkey" FOREIGN KEY ("DeptId")
    REFERENCES public."Department" ("DepartmentId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Specialty_Subject"
    ADD CONSTRAINT "Specialty_Subject_SpecialtyId_fkey" FOREIGN KEY ("SpecialtyId")
    REFERENCES public."Specialty" ("SpecialtyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Specialty_Subject"
    ADD CONSTRAINT "Specialty_Subject_SubjectId_fkey" FOREIGN KEY ("SubjectId")
    REFERENCES public."Subject" ("SubjectId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Student"
    ADD CONSTRAINT "Student_SpecialtyId_fkey" FOREIGN KEY ("SpecialtyId")
    REFERENCES public."Specialty" ("SpecialtyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Subject"
    ADD CONSTRAINT "Subject_ExecutorDeptId_fkey" FOREIGN KEY ("ExecutorDeptId")
    REFERENCES public."Department" ("DepartmentId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Teacher"
    ADD CONSTRAINT "Teacher_EmployeeId_fkey" FOREIGN KEY ("EmployeeId")
    REFERENCES public."Employee" ("EmployeeId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;